# @package _global_

# Wandb config
project: behavior_transformer_repro
experiment: ${env.name}_${experiment.name}

# Hydra saving 
hydra:
  job:
    chdir: True   
  run:
    dir: ./eval_runs/${experiment.name}/${experiment.save_subdir}
  sweep:
    dir: ./train_runs/${experiment.name}/${experiment.save_subdir}
    subdir: ${hydra.job.num}
    # subdir: ${hydra.job.override_dirname}  # Uncomment this line to name the run storing subdirectories after the overriden hyperparameters
    # subdir: ${get_only_swept_params:}  # Uncomment this line to name the run storing subdirectories after the overriden hyperparameters, except the ones instantiated from the command line
