# @package _global_

# Wandb config
project: behavior_transformer_repro
experiment: ${env.name}_${experiment.name}

# Hydra saving 
hydra:
  job:
    chdir: True   
  run:
    dir: ./single_runs/${experiment.name}/${now:%Y.%m.%d-%H.%M.%S}
  sweep:
    dir: ./sweeper_runs/${experiment.name}/${now:%Y.%m.%d-%H.%M}
    subdir: ${get_only_swept_params:}/seed=${experiment.seed}