name: behavior-transformer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - torchvision=0.14
  - pytorch=1.13
  - umap-learn=0.5
  - scikit-learn=1.0.1
  - holoviews=1.14
  - bokeh=2.4.2
  - datashader=0.13
  - seaborn=0.11
  - ipykernel=6.9
  - jupyterlab=3.2
  - pip==22.0.3
  - mpi4py==3.1.3
  - gin-config==0.5.0
  - pip:
    - black==22.3.0
    - mujoco==2.1.3
    - dm-control==1.0.1
    - einops==0.3.2
    - gym==0.21.0
    - hydra-core==1.1.1
    - ipdb==0.13.9
    - imageio==2.13.3
    - wandb==0.12.7
    - shapely==1.8.1.post1
    - networkx==2.8
    - av==9.2.0
    - pybullet==3.2.2
    - protobuf==3.20.1
    - -r requirements.txt
