defaults:
  - _self_
  - encoder: identity
  - action_ae: discretizers/k_means_blockpush_best
  - env: block_pushing_multimodal_fixed_target
  - state_prior: mingpt_blockpush_best
  - env_vars: env_vars

lazy_init_models: True

device: cuda
seed: 42
load_dir: ${env.load_dir}
# Length of history
window_size: 3

# Environment running setup
num_eval_eps: 100
action_batch_size: 1
num_eval_steps: 300
use_state_prior: True
enable_offsets: True
action_update_every: 1
flatten_obs: True
enable_render: True

# Plotting setup
plot_interactions: False
start_from_seen: False
record_video: False

# Wandb setup
project: behavior_transformer_repro_test
experiment: blockpush_eval

hydra:
  job:
    override_dirname: ${experiment}
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${experiment}
    subdir: ${hydra.job.num}
