defaults:
  - _self_
  - encoder: identity
  - action_ae: discretizers/k_means_blockpush_best
  - env: block_pushing_multimodal_fixed_target 
  - state_prior: mingpt_blockpush_best
  - env_vars: env_vars
  - params_sweep: params_sweep

lazy_init_models: True

# Dataset details
train_fraction: 0.95
batch_size: 256
num_workers: 32
window_size: 5

# Training details
num_training_epochs: 1
data_parallel: True
device: cpu
optim: Adam
save_latents: False

lr: 1e-4
weight_decay: 0.1
betas:
  - 0.9
  - 0.95
grad_norm_clip: 1.0
seed: 42

# Prior training details
num_prior_epochs: 350
eval_prior_every: 1
save_prior_every: 1

# Logging frequency
eval_every: 1
save_every: 1

# Wandb config
project: behavior_transformer_repro_test
experiment: blockpush_train

hydra:
  job:
    chdir: True   
  run:
    dir: ./exp_local/${experiment}/${now:%Y.%m.%d-%H.%M.%S}
  sweep:
    dir: ./exp/${experiment}/${now:%Y.%m.%d-%H.%M}
    subdir: ${get_only_swept_params:}/seed=${seed}
    # subdir: ${hydra.sweeper.params}/seed=${seed}
    # subdir: ${hydra.job.override_dirname}/seed=${seed}
